
spring.datasource.url=jdbc:mysql://13.124.233.98:3306/jwt_db?characterEncoding=UTF-8
spring.datasource.username=jang
spring.datasource.password=jang1234
spring.jpa.hibernate.ddl-auto=create

# ?? JWT ???
spring.jwt.secret=SahL5G83mGzrulJzffw-eD7RqphsXluJPBwxu0ncBFo